title: The Bible - Simplified English Edition
description: 
theme: just-the-docs

url: https://simplified.bible

logo: "/assets/logo/logo.jpg"

# Set a path/url to a favicon that will be displayed by the browser
favicon_ico: "/assets/logo/favicon.ico"

# Footer content
# appears at the bottom of every page's main content
# Note: The footer_content option is deprecated and will be removed in a future major release. Please use `_includes/footer_custom.html` for more robust
# markup / liquid-based content.
footer_content: "Copyright &copy; 2023"



# Enable or disable the site search
# Supports true (default) or false
search_enabled: true

search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 3
  # Maximum amount of previews per search result
  # Default: 3
  previews: 3
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 5
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 10
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false

# Google Analytics Tracking (optional)
# Supports a CSV of tracking ID strings (eg. "UA-1234567-89,G-GS1PJ45T73'")
ga_tracking: G-GS1PJ45T73
ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true/nil by default)



