title: The Bible - Simplified English Edition
description: The Bible in Simplified English - Easy to read Scripture for English learners
remote_theme: just-the-docs/just-the-docs
url: https://simplified.bible
logo: "/assets/logo/logo.jpg"

# Set a path/url to a favicon that will be displayed by the browser
favicon_ico: "/assets/logo/favicon.ico"

# Aux links (top right corner)
#aux_links:
# "Learn English with LexiVerses":
#   - "https://lexiverses.app"
#aux_links_new_tab: true

# Footer content
footer_content: 'Copyright &copy; 2024 | <a href="/privacy">Privacy Policy</a> | <a href="/terms">Terms of Service</a> | <a href="https://www.lexiverses.com">Learn English with LexiVerses</a>'

# Enable or disable the site search
search_enabled: true
search:
  heading_level: 3
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

# Google Analytics Tracking (optional)
ga_tracking: G-GS1PJ45T73
ga_tracking_anonymize_ip: true

plugins:
  - jekyll-sitemap
